// Objective-C API for talking to github.com/petejkim/gomoapp Go package.
//   gobind -lang=objc -prefix=Go github.com/petejkim/gomoapp
//
// File is generated by gobind. Do not edit.

#ifndef __GoGomoapp_H__
#define __GoGomoapp_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

FOUNDATION_EXPORT NSString* GoGomoappFooInJSON(NSString* jstr);

FOUNDATION_EXPORT NSString* GoGomoappGoRoutine();

FOUNDATION_EXPORT NSString* GoGomoappHTTPGet(NSString* url);

FOUNDATION_EXPORT NSString* GoGomoappHello(NSString* name);

FOUNDATION_EXPORT long GoGomoappTick();

#endif
