
// Objective-C API for talking to the following Go packages
//
//	github.com/petejkim/gomoapp
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gomoapp_H__
#define __Gomoapp_H__

#include "GoGomoapp.h"
#include "GoUniverse.h"

#endif
